### ISSUE TITLE
Improved containment halls

### ISSUE THREAD

**Issue by StevieGoodman** [StevieGoodman/site_74#76]
I would like to improve the containment halls significantly.
By employing industry standard practices such as greyboxing, I can experiment with different layouts to create a more interesting environment before delving into creating the final product.
I would also like to create separate containment halls for each object class.

https://www.youtube.com/watch?v=AKeUZVikPV8

# Todo
- [ ] Greybox safe-class containment unit
- [ ] Greybox euclid-class containment unit
- [ ] Greybox keter-class containment unit
- [x] Finalise safe-class containment unit
- [x] Finalise euclid-class containment unit
- [x] Finalise meter-class containment unit

**Comment by StevieGoodman** [comment]
To simplify development on this update, the existing containment hall was repurposed, instead of creating a new design.
